### ISSUE TITLE
Cannot seem to write location packet

### ISSUE THREAD

**Issue by MobAction** [ammaraskar/pyCraft#67]
Hello, 

I am receiving the following stack trace. I am attempting to have the client moves when it receives a certain chat string, and am attempting to write the packet from the packet_listener function call. Any advice.example on how to properly do this?:

```
    connection.register_packet_listener(process_location_data, PlayerPositionAndLookPacket)
    def print_chat(chat_packet):
            for chatline in chat_payload.get('extra'):
                concatted_chat += chatline.get("text")
                
            if "!magicstring" in concatted_chat: 
                #current_position = PlayerPositionAndLookPacket
            
                packet = PlayerPositionAndLookPacket()
                packet.PositionAndLook(x=-7400, y=1, z=5319, yaw=160, pitch=160, teleport_id=1, flags=0b11111)

                packet.x = 1.0
                packet.z = 1.0
                packet.y = 1.0

                packet.yaw = 150
                packet.pitch = 150
                
                packet.teleport_id = 1
                
                # Now a relative move
                packet.flags = 0b11111

                #packet.apply(current_position)
                connection.write_packet(packet)
                
                print('position change trigger')
                
                
            print concatted_chat
```

```
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.py",
 line 341, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.py",
 line 319, in _handle_exception
    raise_(*exc_info)
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.py",
 line 339, in run
    self._run()
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.py",
 line 371, in _run
    self.connection.file_object)
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.py",
 line 430, in read_packet
    length = VarInt.read(stream)
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\types.py", line
 93, in read
    raise EOFError("Unexpected end of message.")
EOFError: Unexpected end of message.
```

Thanks much in advance

**Comment by joodicator** [comment]
@MobAction `PlayerPositionAndLookPacket` is a clientbound packet. When you send it, the server terminates your connection without the courtesy of a disconnect message, hence the unexpected end of the stream. `PositionAndLookPacket` is the serverbound packet that you probably intended to use.

The names of these packets do not make this very clear, I realise. It might be difficult to change the names while preserving backward compatibility, but perhaps a warning could be printed when trying to send a clientbound packet to the server.

**Comment by MobAction** [comment]
Awesome. Thanks! I'll give it a try tonight.

**Comment by ammaraskar** [comment]
Hey @MobAction, did you end up getting this to work?

**Comment by MobAction** [comment]
Sorry guys -- slacking hard (and wound up going out of town), should have a moment to follow around on this shortly. Appreciate the expeditious support!

**Comment by MobAction** [comment]
Hi guys,

Still having some sort of issue, here's my code in the ChatMessagePacket listener:

```
          if "!special_chat_words" in concatted_chat: 
            
                packet = PositionAndLookPacket()
                packet.x = 1.0
                packet.z = 0.0
                packet.y = 1.0

                packet.yaw = 150
                packet.pitch = 150

                connection.write_packet(packet)
                
                print('position change trigger')
```


Produces:

```
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.p
 line 341, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.p
 line 319, in _handle_exception
    raise_(*exc_info)
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.p
 line 339, in run
    self._run()
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.p
 line 394, in _run
    raise_(*exc_info)
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.p
 line 358, in _run
    while self.connection._pop_packet():
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\connection.p
 line 194, in _pop_packet
    packet.write(self.socket, self.options.compression_threshold)
  File "C:\Users\mobaction\Desktop\pyCraft-master\minecraft\networking\packets.py",
ne 143, in write
    data = getattr(self, var_name)
AttributeError: 'PositionAndLookPacket' object has no attribute 'feet_y'
```

**Comment by MobAction** [comment]
That one was a gimmie, should have tore into it a bit more..

Added the requisite missing values; and now the code doesn't fail; but the player doesn't move :)

I'm going to give it a more in-depth review shortly, but is there a way to see if the packet is being received but rejected as invalid? On some servers I am kicked, on the local LAN game there is no movement. Curious if I'm specifying something out-of-bounds.

**Comment by ammaraskar** [comment]
Well if you're hardcoding the values in, the server won't allow you to move to just any arbitrary coordinates in one motion. See this example by joodicator which waits for the server to send you your initial position and then moves in a circle relative to that: https://github.com/ammaraskar/pyCraft/issues/62#issuecomment-312612789

**Comment by MobAction** [comment]
I copied a bit of his code, but it didn't work -- so I started changing it up and adding some print staements to isolate the issue.

It looks like I'm not receiving a position and look packet from the server, as I never see it on the console..


```
    def h_position_and_look(packet):
        packet.apply(pos_look)
        print 'GOT POSITION PACKET'

    connection.connect()
    connection.register_packet_listener(h_position_and_look, PlayerPositionAndLookPacket)  

```

**Comment by joodicator** [comment]
@MobAction Might it be that you have a race condition where the packet is received before you register the listener? Try connecting after setting the listener.

**Comment by em202020** [comment]
Im also having an issue with not receiving the PlayerPositionAndLookPacket after connecting.  I have copied the example code from #62 verbatim, and it is not getting the packet.  I have setup the packet listener before the client has connected, as well.

**Comment by joodicator** [comment]
@em202020 It works for me with a vanilla 1.12.1 server (and using Pythons 2.7.13 and 3.6.1) -- and using the latest commit of pyCraft, namely 46e058dd080453b2081ecfad37f503d8ae531de1. If your configuration is different and this code doesn't work for you, please let us know the details in case there is a bug in pyCraft or the example code.

Regarding the call to `wait()` on line 27: this is the standard pattern for waiting on condition variablees: the lock is released during the call to `wait()` and then reacquired when it ends. See: https://docs.python.org/3/library/threading.html#threading.Condition.wait.

I don't think these are related, but also make sure the server is in offline mode, the player's path is unobstructed, and preferably the player is in creative mode so they can walk through the air with problems.

**Comment by em202020** [comment]
I have tested it on windows and on Linux, both with the same result.
I attempted to use a virtual environment to prevent outside conflicts, leaving only these packages in use.
![image](https://user-images.githubusercontent.com/1835590/29492047-06f24dae-8524-11e7-9da3-d7579a5e9afe.png)

The server I am testing it on is 1.11.2.  I attempted to change the initial_version to 1.11.1, but it did not work.  When I created a 1.12.2 server though, it did work.

What reason would it have to work on 1.12.1, but not 1.11.2?

**Comment by joodicator** [comment]
PlayerPositionAndLookPacket was broken for 1.11.2, with the wrong packet ID configured. I think this was my fault - my apologies. This is fixed in 9765e936c9c2558022d361d534769f6d87ccd902.

**Comment by em202020** [comment]
Huh, I noticed some of the packet IDs were weird before I went to bed last night, and had changed them in the same way that you did, though it still didnt work for me.  Though after recloning the repo, it did.  Thanks for getting this fixed 👍

**Comment by MobAction** [comment]
Hi guys,

Just wanted to follow up. After DLing the latest including the fix, I AM receiving the location packet, but I am still not able to move the player. It appears to have no effect:

        if CTEP.parseChatEvent(chat_packet) == "test":
            print 'bout to move'
            print pos_look.x
            print pos_look.y
            print pos_look.z
            print pos_look.yaw
            print pos_look.pitch
            pos_look.yaw = (pos_look.yaw + 1.0) % 360.0
    
            # Move forward 0.1m.
            pos_look.x -= 0.1 * math.sin(pos_look.yaw * math.pi / 180.0)
            pos_look.z += 0.1 * math.cos(pos_look.yaw * math.pi / 180.0)
        
            connection.write_packet(PositionAndLookPacket(
                x         = pos_look.x,
                feet_y    = pos_look.y,
                z         = pos_look.z,
                yaw       = pos_look.yaw,
                pitch     = pos_look.pitch,
                on_ground = True))

**Comment by em202020** [comment]
Is that block of code only called when you receive the PlayerPositionAndLookPacket?  From my experience, you only get that packet when you join, and when your character makes an invalid movement (and the server tries to move you to a valid one, eg. if you try to move feet_y into the ground).  Your problem might be that the movement might be too small to notice if it is only called once.

**Comment by MobAction** [comment]
It's being called upon parsing chat for a keyword. Good point on it potentially being too little to notice. I increased it by 1, but still doesn't work. What's the maximum I can move in one packet?
            connection.write_packet(PositionAndLookPacket(
                x         = pos_look.x + 1,
                feet_y    = pos_look.y,
                z         = pos_look.z + 1,
                yaw       = pos_look.yaw,
                pitch     = pos_look.pitch,
                on_ground = True))

**Comment by joodicator** [comment]
@MobAction The fact that you do not appear to be updating `pos_look` with your target coordinates might be causing problems. It means that each time that command is issued, you will be moving to (approximately) the same location each time. If you want to increase the distance moved, you should rather do it here:
```python
        pos_look.x -= 1 * math.sin(pos_look.yaw * math.pi / 180.0)
        pos_look.z += 1 * math.cos(pos_look.yaw * math.pi / 180.0)
```

**Comment by joodicator** [comment]
I'm closing this issue for now as there have been no comments for 8 months, but if you have further questions feel free to post them here.
